# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adb7e17db43191ae87c022f1b256b174f85f3d0c0e167c414eaef041ee648007e86ccabb25490ca6f60f246997fa9d0ed7a2e940e8adf324c6d6f12277cf1743

test:
  secret_key_base: eefeb97cc856e6ea5278a9eb83e7291245ba1b0f17c544d25ff75d5ba2bab93d4aea7005eaeae56a7c67dbf9fb2c497b1676b9a955cdf40bd7de7d9c404def59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
